import { configureStore } from '@reduxjs/toolkit';
import { reducer as app } from '../slices/App';

// Start of store import code generated by oxgen. DO NOT EDIT.
import { api as objects } from '../slices/Object';
// End of store import code generated by oxgen. DO NOT EDIT.

export const store = configureStore({
  reducer: {
    app,
    // Start of store reducer code generated by oxgen. DO NOT EDIT.
    [objects.reducerPath]: objects.reducer,
    // End of store reducer code generated by oxgen. DO NOT EDIT.
  },
  middleware: getDefaultMiddleware =>
    getDefaultMiddleware()
      // Start of store middleware code generated by oxgen. DO NOT EDIT.
      .concat(objects.middleware),
  // End of store middleware code generated by oxgen. DO NOT EDIT.
});

// Infer the `RootState` and `AppDispatch` types from the store itself
export type RootState = ReturnType<typeof store.getState>;

// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
export type AppDispatch = typeof store.dispatch;
